config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards do
    resources :reservations, only: [ :new, :create ]
  end

  resources :users, only: [ :show ] do
    resources :reservations, only: [ :show, :index ]
  end

  resources :reservations, only: [ :update, :edit ] do
    resources :reviews, only: [ :create ]
  end

  resources :reviews, only: [ :destroy ]
  resources :reservations, only: [ :destroy ]

  get '/dashboard', to: 'pages#dashboard'
  get '/search/category/:category', to: 'boards#filter'
  get '/search', to: 'boards#filter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord

  CATEGORY = ["all","shortboard", "hybride", "longboard", "fish", "egg", "enfant", "stand up paddle", "mini malibu", "évolutive", "gun", "foil", "planche en mousse", "mid-length", "évolutive / hybride", "deco", "vintage", "retro","rétro"]
  # GEOVODER SET UP
  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_zipcode? && :will_save_change_to_street? && :will_save_change_to_city? && :will_save_change_to_country?

  has_one_attached :photo
  belongs_to :user

  validates :category, :inclusion=> { in: CATEGORY}



  has_many :reservations
  has_many :reviews, through: :reservations

  scope :active, -> { where("status = ?", "active") }

  scope :select_categories, ->(arr) {where('category IN (?)', arr)}



  def full_address
    "#{street}, #{zipcode}, #{city}, #{country}"
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = ["1", "2", "3", "4", "5"]
  belongs_to :user
  belongs_to :reservation
end

app/models/user.rb
class User < ApplicationRecord

  devise :omniauthable, omniauth_providers: [:facebook]
  has_one_attached :photo
  
  #Watch out for the form !
  has_many :reservations
  has_many :boards
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_for_facebook_oauth(auth)
      user_params = auth.slice("provider", "uid")
      user_params.merge! auth.info.slice("email", "first_name", "last_name")
      user_params[:facebook_picture_url] = auth.info.image
      user_params[:token] = auth.credentials.token
      user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
      user_params = user_params.to_h

      user = User.find_by(provider: auth.provider, uid: auth.uid)
      user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
      if user
        user.update(user_params)
      else
        user = User.new(user_params)
        user.password = Devise.friendly_token[0,20]  # Fake password for validation
        user.save
      end

      return user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :filter]

  def index
    @categories = Board::CATEGORY
    @boards = policy_scope(Board).order(created_at: :desc)
  end

  def filter
    @boards = params[:board_category] == "all" ? Board.all : Board.select_categories(params[:board_category].split(','))
    @boards = @boards.near(params[:place], 100)  if params[:place]
    authorize @boards
    array = []
    @boards.each do |board|
      array << board.as_json.merge({"image"=>board.photo.key})
    end
    render json: array.to_json
  end

  def show
    @board = Board.find(params[:id])
    @reservation = Reservation.new
    @review = Review.new
    authorize @reservation
    gon.board_reservations = @board.reservations
    authorize @board
  end

  def new
    @board = Board.new
    authorize @board
  end

  def create
    @board = Board.new(board_params)
    authorize @board
    @board.user = current_user
    if @board.save
      redirect_to dashboard_path, alert: "Your listing has been made successfully!"
    else
      render 'new'
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.update(board_params)
    redirect_to board_path(@board)
  end

  def destroy
    @board = Board.find(params[:id])
    authorize @board
    @board.destroy
    redirect_to dashboard_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :brand, :length, :thickness, :width, :volume, :price,
    :city, :zipcode, :street, :photo, :status, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @categories = Board::CATEGORY
  end

  def dashboard
    @user = current_user
    @review = Review.new
    @reviews = @user.reviews
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to dashboard_path
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @revervations = Reservation.all
  end

  def create
    @board = Board.find(params[:board_id])
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    @reservation.board = @board
    @reservation.user = current_user
    if @reservation.save
      redirect_to dashboard_path, alert: "Your reservation has been made successfully!"
    else
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.destroy
    redirect_to dashboard_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @rating = Review::RATING
    @reviews = Review.all
  end

  def create
    @review = Review.new(review_params)
    authorize @review
    @review.reservation_id = params["reservation_id"]
    @review.user = current_user
    if @review.save!
      redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to dashboard_path
  end

  def review_params
    puts 'inside params'
    params.require(:review).permit(:name, :rating, :content)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params[:user])
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.erb
<div class="container main_container">
<h1>All our boards</h1>

<%# <div class="filters">
<%= form_tag boards_path, method: :get do %>
  <%# <%= select_tag "board_category", options_for_select(Board::CATEGORY) %>
  <%# <%= text_field_tag :place, %>
    <%# params[:place], %>
    <%# class: "form-control", %>
    <%# placeholder: "Where do you want to surf" %>
  <%# %>
  <%# <%= submit_tag "Let see", class: "btn btn-primary" %> 
<%# <% end %> 
<%# </div> %> 

<br>

  <div class="content" style="margin-left: 250px">
    <div class="boards">
      <% @boards.each do |board| %>
        <div class="board">

      <div class="card-board">
        <div class="card-board-infos">
          <div class="card-board-infos-top">
            <a href="/boards/${board.id}"><h2>${board.name}</h2></a>
            <p>dims : ${board.length} X ${board.width} X ${board.thickness}-${board.volume}</p>
          </div>
          <div class="card-board-infos-top">
            <p>${board.category}</p>
            <p>${board.price}</p>
          </div>
        </div>
        <img src="http://res.cloudinary.com/dn9jutvov/image/upload/${board.image}" />
      </div>

        </div>
      <% end %>
    </div>
    <div id="map"
      style="width: 100%; height: 600px;"
      data-markers=""
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>


  <div class="sidebar">
    <%= render "shared/filter_sidebar" %>
  </div>

</div>

  <br>

app/views/boards/new.html.erb
<div class="container-new justify-content-center">
      <div class="center-form">

        <h1>Add a board to rent</h1>

        <%= simple_form_for @board do |f| %>

          <%= f.input :name, :placeholder => 'Type here' %>
          <div class="wrap">
            <%= f.input :brand, :placeholder => 'ex: Channel Island' %>
            <%= f.input :category, collection: Board::CATEGORY %>
          </div>

          <div class="wrap">
            <%= f.input :length, :placeholder => 'UI: inches' %>
            <%= f.input :thickness, :placeholder => 'UI: inches' %>
          </div>

          <div class="wrap">
            <%= f.input :width, :placeholder => 'UI: inches' %>
            <%= f.input :volume, :placeholder => 'UI: L' %>
          </div>

          <%= f.input :street, :placeholder => "Avenue de l'impératrice" %>

          <div class="wrap">
            <%= f.input :city, :placeholder => 'Biarritz' %>
            <%= f.input :zipcode, :placeholder => '64200' %>
          </div>

          <%= f.input :price, :placeholder => 'Euro' %>
          <%= f.input :photo, as: :file %>

          <center><%= f.button :submit, class: 'btn btn-primary btn-margin' %></center>
        <% end %>
    </div>
    <div id="new-image"> <%= image_tag "new-surf.jpg", alt: "alttext" %> </div>
</div>

app/views/boards/show.html.erb
<div class="container">
  <h1><%= @board.name %> </h1>

  <div class="row card-product">
    <li><%= cl_image_tag @board.photo.key, height: 300, width: 400, crop: :fill %></li>
    <div class="card-product-infos">
      <ul>
        <li>Length : <%= @board.length %></li>
        <li>Thickness : <%= @board.thickness %></li>
        <li>Width : <%= @board.width %></li>
        <li>Volume : <%= @board.volume %></li>
      </ul>
    </div>
  </div>

  <!-- Button trigger modal -->
  <center><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"> Book a board </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Book a board</h5>
          <button type="btn btn-gradient" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render "reservations/new" %>
        </div>
        <div class="modal-footer">
          <button type="button" style='display:none' class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<div class="container-review">
  <h1>Board's Review : </h1>

    <% @board.reviews.each do |review| %>
      <div class="review_card">
        <div class="card-review-infos">
          <ul>
            <li><div><%= review.user.first_name %></div></li>
            <li><div> <strong>Rating : <%= review.rating %></strong></div></li>
            <li><div> <%= review.content %></div></li>
            <li><div><p>Created : <%= review.created_at.to_formatted_s(:long_ordinal) %></p></div></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>


    <title>OpenQuiver</title>

     <%= Gon::Base.render_data %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="special_wrap">
        <%= yield %>
    </div>
  

     <div class="footer">
    <div class="list-inline">
      <ul>
        <li>
          <a href=""><i class="fab fa-twitter"></i></a>
        </li>
        <li>
          <a href="" ><i class="fab fa-instagram"></i></a>
        </li>
        <li>
          <a href=""><i class="fab fa-facebook"></i></a>
        </li>
        <li>
          <a href=""><i class="fab fa-github"></i></a>
        </li>
      </ul>
        <div class="footer_img">
          <p>This website was coded by smart developper at Le Wagon. <i class="fas fa-laptop-code"></i></p>
          🏄🏼‍♂️
        </div>
    </div>
  </div>
  </body>
</html>

<style>
.special_wrap {
    padding-top: 50px;
  padding-bottom: 50px;

}

</style>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Hello <%= @user.first_name %> !</h1>
  <br>
  
  <!-- Here is the list of the ongoing reservations -->
  <h2>You have <%= @user.reservations.count %> reservation(s) :</h2>

  <% if @user.reservations.blank? %>
    <div class="card-dashboard-blank">
    <h2> You do not have any reservations yet.</h3>
    <p> <%= link_to "All boards", boards_path %></p>
    </div>
  <% else %>
  <ul>
    <% @user.reservations.each do |reservation| %>
      <div class="card-dashboard">
        <% if reservation.board.photo.attached? %>
        <li><%= cl_image_tag reservation.board.photo.key, height: 300, width: 400, crop: :fill %></li>
        <% end %>
        <div class="card-dashboard-infos">
          <h2> You have booked <%= reservation.board.name %></h2>
          <p> from <strong><%= reservation.start_date.to_formatted_s(:long_ordinal) %></strong> to <strong><%= reservation.end_date.to_formatted_s(:long_ordinal) %></strong>.</p>
          <p><%= link_to "Cancel my reservation", reservation_path(reservation), method: :delete, remote: true, data: { confirm: "Are you sure?" } %></p>
        </div>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Leave a review</button>

<!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Leave a review</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= render 'reviews/new', reservation: reservation %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
<% end %>

<!-- Here is the list of the ongoing listings -->

  <h2>You have <%= @user.boards.count %> ongoing listing(s) :</h2>

  <% if @user.boards.blank? %>
    <div class="card-dashboard-blank">
    <h2> You do not have any listings yet.</h2>
    <p> <%= link_to "List a board", new_board_path %></p>
    </div>
  <% else %>
    <ul>
      <% @user.boards.each do |board| %>
        <div class="card-dashboard">
          <% if board.photo.attached? %>
          <li><%= cl_image_tag board.photo.key, height: 300, width: 400, crop: :fill %></li>
          <% else %>
           <li><%= image_tag 'no-image-icon.png', height: 300, width: 400, crop: :fill %></li>
          <% end %>
          <div class="card-dashboard-infos">
            <h2> You listed <%= board.name %></h2>
            <p><%= link_to "Cancel my listing", board_path(board), method: :delete, remote: true, data: { confirm: "Are you sure?" } %></p>
          </div>
        </div>
         </ul>
      <% end %>
  <% end %>

    <h2>Reviews : </h2>

      <% @reviews.each do |review| %>
        <div class="review_card">
          <div class="card-dashboard-infos">
            <ul>
              <li><div><%= @user.first_name %></div></li>
              <li><div><%= review.reservation.board.name %></div></li>
              <li><div> <strong>Rating : <%= review.rating %></strong></div></li>
              <li><div> <%= review.content %></div></li>
              <li><div><p>Created : <%= review.created_at.to_formatted_s(:long_ordinal) %></p></div></li>
            </ul>
          </div>
          <p> <%= link_to "Delete Review", review_path(review), method: :delete, remote: true, data: { confirm: "Are you sure?" } %></p>
        </div>
      <% end %>

      </div>
  
</div>

    <div class="card-dashboard-cheat">
 
    </div>


    

app/views/pages/home.html.erb
<div class="container-home">
    <div id="text">
      <h1>Open Quiver</h1><br>
      <h2>Rent a board anywhere. Get paid to share yours.</h2><br>
      <p> The largest & most trusted online marketplace for surfers to rent out and share boards.</p>
     <%= form_tag boards_path, method: :get do %>
      <%= text_field_tag :query,
        params[:place],
        class: "form-control",
        placeholder: "Where do you want to surf"
      %> <br>
      <center><%= submit_tag "Let see", class: "btn_blue" %></center>
    <% end %>
    </div>
    <div id="home-image"> <%= image_tag "https://source.unsplash.com/35muyqODIHA", alt: "alttext" %> </div>
</div>

app/views/reservations/_new.html.erb
<h1>New Reservation</h1>

<%= simple_form_for [@board, @reservation] do |f| %>
<%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker" , id: "range_start"} %>
<%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker" , id: "range_end"} %>
<%= f.button :submit, "Go", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to board list", boards_path %>

app/views/reservations/index.html.erb
index.html.erb

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= simple_form_for [@board, @reservation] do |f| %>
<%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker" , id: "range_start"} %>
<%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker" , id: "range_end"} %>
<%= f.button :submit, "Go", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to board list", boards_path %>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [reservation, @review] do |f| %>
  <%= f.input :rating, collection: Review::RATING %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/shared/_filter_sidebar.html.erb
<section class="mb-4">

  <p class="font-weight-bold mb-3"> Address </p>
  <%= form_tag boards_path, method: :get, class: "md-form md-outline mt-0" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control mb-0",
      placeholder: "Enter an address"
    %>
    <br>

    <p class="font-weight-bold mb-3"> Category </p>
      <div class="all-button">
      <%= check_box_tag "categories[all]", "all", checked: "checked"  -%>
        <%= label_tag("all", "all", class: "form-check-label small text-uppercase card-link-secondary") %>
        <br>
      </div>
      <div class="cat-buttons">
      <% @categories.reject{|cat| cat=="all"}.each do |category| %>
        <%= check_box_tag "categories[#{category}]", category   -%>

        <%= label_tag(category, "#{category}", class: "form-check-label small text-uppercase card-link-secondary") %>
        <br>
      <% end %>
      </div>
    <br>

    <p class="font-weight-bold mb-3"> Price range  </p>

    <%= text_field_tag :price,
      params[:price],
      class: "js-range-slider"
    %>

    <br>

    <%= submit_tag "Search", class: "btn btn-gradient" %>

  <% end %>

</section>

<script>
  var $range = $(".js-range-slider");

  $range.ionRangeSlider({
        skin: "round",
        type: "double",
        grid: false,
        min: 0,
        max: 50,
        from: 15,
        to: 25,
        prefix: "€"
    });

</script>

<style>
  body {
    font-family: Arial, sans-serif;
    font-size: 12px;
}
.range-slider {
    position: relative;
    height: 80px;
}
</style>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    🏄🏼‍♂️
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List a board", new_board_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% avatar_url = current_user.facebook_picture_url || "https://avatars.githubusercontent.com/u/414418?s=400&u=acbec8c5ad43dd74e4970d8b340244ddb7d81b27&v=4" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "List a board", new_board_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>